package com.anikhil.springjdbcdemo.utils;

public class ColumnMapping {
    private String columnName;
    private boolean isPrimaryKey;
    private boolean isAutoGenerated;

    public ColumnMapping(String columnName, boolean isPrimaryKey, boolean isAutoGenerated) {
        this.columnName = columnName;
        this.isPrimaryKey = isPrimaryKey;
        this.isAutoGenerated = isAutoGenerated;
    }

    public String getColumnName() {
        return columnName;
    }

    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    public boolean isPrimaryKey() {
        return isPrimaryKey;
    }

    public void setPrimaryKey(boolean primaryKey) {
        isPrimaryKey = primaryKey;
    }

    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        isAutoGenerated = autoGenerated;
    }
}
