package com.anikhil.springjdbcdemo.utils;

import com.anikhil.springjdbcdemo.sqldatatypes.SQLDataType;

public class ColumnMapping {
	private final String columnName;
	private final boolean isPrimaryKey;
	private final boolean isAutoGenerated;
	private final SQLDataType sqlDataType;

	public ColumnMapping(String columnName, boolean isPrimaryKey, boolean isAutoGenerated, SQLDataType sqlDataType) {
		this.columnName = columnName;
		this.isPrimaryKey = isPrimaryKey;
		this.isAutoGenerated = isAutoGenerated;
		this.sqlDataType = sqlDataType;
	}

	public String getColumnName() {
		return columnName;
	}

	public boolean isPrimaryKey() {
		return isPrimaryKey;
	}

	public boolean isAutoGenerated() {
		return isAutoGenerated;
	}

	public SQLDataType getSqlDataType() {
		return sqlDataType;
	}
}
